### ISSUE TITLE
Is there a way to render limited area maps in Appalachia similar in scale to those available for interior cells?

### ISSUE THREAD

**Issue by pcrov** [AHeroicLlama/Mappalachia#107]
I'd basically like to zoom in further within Appalachia. It'd be useful for making making maps of events, for example maps showing the possible locations of meat bags in Eviction Notice, robots in fasnacht, or even just the layout of things around the Whitespring. The satellite map comes close in some cases but lacks resolution.

Is there any way to do this now or possible to add in the future?

**Comment by AHeroicLlama** [comment]
Thanks for the request. In the mean time I can suggest the compromise of reducing the size and lind width of plot icons (Plot Settings > Plot Style Settings), and simply cropping and resizing the outputted image.

When we talk about resolution there are a few angles to consider - the background images are provided in 4096^2 resolution. This is the maximum resolution shipped with the game, so no higher resolution image is generally available.

We can talk about the resolution of the plots (or their accuracy) - however these are already very highly accurate, so I don't believe further resolution is required.

Finally there is the resolution of the plot icon itself. This is however limited by the size of the output image for which they are being plotted onto, which could be changed with some work.

On the theme of increasing the output resolution, the rendered background image could be shipped as 16k^2, but fairly significant work would be required for this at the moment.

**Comment by AHeroicLlama** [comment]
Now tracking this under #131
Thanks for initially requesting.
