### ISSUE TITLE
I am not able to launch it.  Here is the error.

### ISSUE THREAD

**Issue by GittyAub** [AHeroicLlama/Mappalachia#35]
![Error _ Oby](https://user-images.githubusercontent.com/38766718/132791187-a06321fe-772e-47c7-bcdd-89523464c627.png)

**Comment by GittyAub** [comment]
After checking the possibilities listed in the pop-up I found no issue...

Thank You...
**_Important for others_**
It looks like I have to update my 7zip.
After unzipping 1.4.0.0 using W10's built in unarchiver, it is running A-OK 

I have been unzipping all types of archives for quite a while with no issue till now.

**Comment by AHeroicLlama** [comment]
Closing now as this has been identified as release not being properly unzipped. Without being able to replicate it appears the .db file was not unzipped as expected. For anyone interested Mappalachia releases are compressed using powershell Compress-Archive (see https://github.com/AHeroicLlama/Mappalachia/blob/master/Mappalachia/package_release.bat)
