### ISSUE TITLE
Elements misplaced at 150% scaling (on primary display)

### ISSUE THREAD

**Issue by frame** [AHeroicLlama/Mappalachia#49]
On Windows 10 with a 4K display at 150% scaling the UI doesn't look correct:

![capture_20220413_001554](https://user-images.githubusercontent.com/339569/163064995-aa36d581-41e9-4a84-8e4c-8aa039692a3d.jpg)

![capture_20220413_001613](https://user-images.githubusercontent.com/339569/163064999-7c127898-e149-4578-84e1-197c3a1deb3a.jpg)

Moving the application to a secondary screen with 100% scaling doesn't help either: the layout doesn't get re-arranged.

**Comment by AHeroicLlama** [comment]
Relates to https://github.com/AHeroicLlama/Mappalachia/issues/25

**Comment by AHeroicLlama** [comment]
Fixed under development commit f13f006fb31fd38c79eadb4c87a14795998a6833
Pending more testing before release patch.
Thanks again for help testing @frame
