### ISSUE TITLE
Map markers no longer showing with latest release (1.7.0.1)

### ISSUE THREAD

**Issue by brookescott87** [AHeroicLlama/Mappalachia#65]
With the latest release (1.7.0.1), enabling map markers (icons and/or text) seems to no longer be functional.  They worked as expected in release 1.6.1.1.

**Comment by AHeroicLlama** [comment]
Confirmed - taking a look now. Thanks for the report

**Comment by AHeroicLlama** [comment]
Caused by 596d9e82cc694cd3cd1e23228ed1477fb62c0658

**Comment by AHeroicLlama** [comment]
Thanks again for the report @brookescott87 - the fix has now been released
