### ISSUE TITLE
Shapes for multiple items not working

### ISSUE THREAD

**Issue by Belickade** [AHeroicLlama/Mappalachia#67]
I have 3 different items selected for map icons. I have 3 shapes added under plot style settings each with a different shape (a diamond for shape 1, a circle for shape 2 and a square for shape 3. Only Shape 1 and 2 change while shape 3 uses the shape I selected for shape 2. I have tried removing all shapes and starting over but once I go over 2 shapes the same thing happens.

**Comment by AHeroicLlama** [comment]
I can't reproduce this. Whenever Mappalachia needs a new icon it will first use a new color, it will only use a new shape when it runs out of colors of that shape. So for example if you have 5 colors and 3 shapes, you need 15 'legend groups' (Read: "unique items unless you changed this") plotted before icons are reused.

See my example screenshot - 1 color x 3 shapes, all 3 shapes are used before being repeated.

![image](https://user-images.githubusercontent.com/10856550/192617296-71e8127d-739b-4b17-a74a-b71c63089047.png)

Do you mind sharing images of your Plot Style Settings menu and the output, along with the 'items to plot' list - as the legend group here may also interfere

**Comment by Belickade** [comment]
Yeah, I'm not sure if it's user error on my part or what.

Here is what I'm doing exactly:

I want to have 3 different items tracked. Bobbleheads, Caps Stashes and Magazines. I lookup each entry and add them one by one. The Legend Group shows as 0 for the first entry, 1 for the second and 2 for the third. I then go into plot style settings. I add the first color and choose a shape for it. I then add a second, different color, and a different shape. Up to this point I have 2 different colors, and 2 different shapes. I then add a third color with a different shape which results in it inheriting shape 2's shape.

![1](https://user-images.githubusercontent.com/48949063/192621358-6de4cdad-a70f-4b78-9270-4ed232e75af1.jpg)
![2](https://user-images.githubusercontent.com/48949063/192621373-c2dd810d-e94e-487e-a35c-ce347836a583.jpg)
![3](https://user-images.githubusercontent.com/48949063/192621388-870562fa-7b5f-4bc6-a145-dc896b8bcd35.jpg)
![4](https://user-images.githubusercontent.com/48949063/192621394-9e7e5ebe-9577-4548-ac96-a73fb0b53476.jpg)

**Comment by AHeroicLlama** [comment]
Thanks, I think this is an issue of understanding - the color palette and shape palette are entirely independent.
It will dynamically draw shape 1 in all colors, before then shape 2 in all colors, and so on. (If it needs to of course)

Based on you mapping 3 things, the behaviour is as expected - all items use shape 1 with the 3 colors defined.
If you added a 4th item, it would then use shape 2. Then not until your 7th item would it use shape 3. (This is based on you still using 3 colors.)

This is documented [here](https://github.com/AHeroicLlama/Mappalachia/blob/master/User_Guides/Customization.md#colors-and-shapes).

Let me know if that explains it

**Comment by Belickade** [comment]
I wanted to have each item have a unique shape and color so I could easily differentiate items without having to always refer to a legend. I feel it also makes items that are in close proximity to each other easier to see.

I can't say I really understand the dynamically generated colors and shapes thing. Feels unintuitive to have the user set up a shape and color only for the program to spit out said shape/color based on a value the user has no way of interpreting. 

Anyways, thanks for clearing that up. I think I'll just plot a single item per map for now to keep it more readable for my use.
