### ISSUE TITLE
[Feature Request] Export in dds format

### ISSUE THREAD

**Issue by MotiasNotMe** [AHeroicLlama/Mappalachia#82]
Suggestion:
Add the ability to export maps in dds format with a choice of compression/loose.

I think this can be done using tools such as:
[Nvidia texture tools exporter](https://developer.nvidia.com/nvidia-texture-tools-exporter)
or
[Intel ispc texture compressor](https://software.intel.com/en-us/articles/fast-ispc-texture-compressor-update)

**Comment by AHeroicLlama** [comment]
Thanks for the suggestion, I understand this request is ultimately aimed at enabling maps to be modded into the game?
Unfortunately I would consider it feature bloat to add this complex capability to Mappalachia. There are plenty of other tools available which can convert to DDS (probably better too), so this feature doesn't really need to be part of Mappalachia itself. I would simply suggest that users take the output from Mappalachia and make the conversion themselves.
