### ISSUE TITLE
[FEATURE REQUESTS] Map titles and grey icons 

### ISSUE THREAD

**Issue by Anarasha** [AHeroicLlama/Mappalachia#86]
If this is already a part of Mappalachia then I will admit to being blind and take my shame on the nose :p 

That said, if I am NOT blind, I would like to see the following features: 
- An option to add a title to the bottom of the map. This is to integrate with stuff like Uni Map or just to title your maps 
- The option to create grey icons so any icon shown on the map that you have not yet discovered(hence no icon shown on top of it) is grey, clearly indicating undiscovered

**Comment by AHeroicLlama** [comment]
Thanks for the suggestions @Anarasha - I have the following questions;

- About the titling - although I'm conscious of bloating Mappalachia with features which other software already does better, this does sound straightforward to implement and use, and may see use from a portion of users. I would highlight that any text formatting options however would probably be out of scope. If I countered by suggesting it's maybe more appropriate for you to use a third party image editor, would you have any counterarguments?

- Regarding grey icons, am I correct that this is to support a scenario where the outputted map image is modded into the game UI? It's easy to implement as long as I can find a suitable home for it in the menus, I just want to understand the drive behind the request.

Thanks again for your input

**Comment by Anarasha** [comment]
> If I countered by suggesting it's maybe more appropriate for you to use a third party image editor, would you have any counterarguments?

Well, I don't know how many people make custom maps like I do, but if we assume it's enough to matter, I do feel like having the option to add a title to the bottom of the map(perhaps right below West Virginia, or as a title above the current icon legend) would be super useful when making 4-5 different maps for a mapbook. But if almost no one does that, it IS a bit of a specific feature request, but that's my main argument for implementing it :-) 
If you feel it's best not to add to Mappalachia to be careful not to bloat it, I will definitely get that, you know best about this stuff :-) 


> Regarding grey icons, am I correct that this is to support a scenario where the outputted map image is modded into the game UI? It's easy to implement as long as I can find a suitable home for it in the menus, I just want to understand the drive behind the request.

Yes, basically I use Mappalachia to make custom maps for the mod Uni Map :-) It is very nice to have blank icons that are greyed out, so much so that I used photo editing software to make one for my map book :-) When doing maps currently, if you enable icons on the maps, they're blue like discovered locations and that can get really confusing really fast

**Comment by AHeroicLlama** [comment]
Thanks - I've been able to implement both of these features as they were relatively simple. See examples below. Would you have any feedback? I've also set it so that the default filename of the map when exporting to file will be the map title, if set.

https://i.imgur.com/HqR5jkS.jpg
https://i.imgur.com/d45vJvY.jpg

**Comment by Anarasha** [comment]
> Thanks - I've been able to implement both of these features as they were relatively simple. See examples below. Would you have any feedback? I've also set it so that the default filename of the map when exporting to file will be the map title, if set.
> 
> https://i.imgur.com/HqR5jkS.jpg https://i.imgur.com/d45vJvY.jpg

That's amazing, thank you :D 

The only feedback that pops to mind is the use of font. As it's a title, something more blocky and bold, but not italic, might serve the purpose better? Give Century Gothic Bold a shot if that's something you wanna spend more time on :-) 
Also I don't know if that would stray too far from a default map, but I got the idea of simply removing the text in the West Virginia box and use that as a title background? I don't know if that's me overthinking it? Or maybe adding a white box behind black text as an overlay option.


As for the auto naming the map as the title, that was honestly a stroke of brilliance, 11/10 thumbs up!

**Comment by AHeroicLlama** [comment]
Thanks - yeah I wasn't sure about the font too - Bold and slightly larger works (see below). Using a new font face entirely isn't preferable as I may need to ship the font file with the Mappalachia download, so sticking to a single font is better (it's also more consistent design-wise). I'll play around with the size and styling though.
Reagrding changing the background, that'd mean editing the underlying base map image which again feels like too much? And then if there was no title it'd just be a blank space (or I need to ship a second version of the map image). I also need to be cautious about the placement/size of any text/backgrounds so as not to obscure interior maps (also see below)

https://i.imgur.com/J2xqFDs.jpg

**Comment by Anarasha** [comment]
> Thanks - yeah I wasn't sure about the font too - Bold and slightly larger works (see below). Using a new font face entirely isn't preferable as I may need to ship the font file with the Mappalachia download, so sticking to a single font is better (it's also more consistent design-wise). I'll play around with the size and styling though. Regarding changing the background, that'd mean editing the underlying base map image which again feels like too much? And then if there was no title it'd just be a blank space (or I need to ship a second version of the map image). I also need to be cautious about the placement/size of any text/backgrounds so as not to obscure interior maps (also see below)
> 
> https://i.imgur.com/J2xqFDs.jpg

Yeah I figured editing the map to do that might be too much.
But the new font changes look great! :-) if shipping a second font isn't viable then I'd say this is as good as you can get it. 
Thank you for taking the time to add these things in :-)

**Comment by AHeroicLlama** [comment]
Implemented with todays release 1.7.6.0
Thanks again!

PR https://github.com/AHeroicLlama/Mappalachia/pull/87
